### ISSUE TITLE
openbayes部署方法

### ISSUE THREAD

**Issue by Kedreamix** [signcl/openbayes-serving-examples#2]
该方法是否只局限于openbayes，还是可以在任何自己的服务器上进行部署

**Comment by sparanoid** [comment]
虽然理论上可以用我们的镜像自己在本地运行，但需要一些工作，因此目前只限于 OpenBayes 平台

**Comment by Kedreamix** [comment]
非常感谢你的回答，我已经成功在自己本地运行了，不过我还有一个小问题，就是默认的时候端口为25252，有对应的参数来改变端口么

**Comment by Kedreamix** [comment]
我发现好像没有对应的参数可以去修改这个端口port，最后我修改库中的源代码解决了这个问题，还是非常感谢你的回答，谢谢
